grammar := productions

productions := production newline productions
productions := production

production := nonterminal space? produces space? tokens?

tokens := token space tokens
tokens := token

token := nonterminal
token := terminal

nonterminal := [^ \t\n\r:"]+

terminal := '"' string_char* '"'

string_char := "\\\\"
string_char := "\\" '"'
string_char := [^"]

produces := ":="

space := space_char+

space_char := " "
space_char := "\t"

newline := space? newline_char space?
